'use strict';

// ─── Normal Events (single participant) ──────────────────────────────────────
const EVENTS = [
  {
    emoji: '📚',
    title: 'Help Carry Textbooks',
    description: 'A teacher is struggling to move several stacks of textbooks across campus before class starts. Someone needs to lend a hand!',
    cooperative: false,
  },
  {
    emoji: '🧹',
    title: 'Campus Clean-Up Crew',
    description: 'The courtyard is a mess after yesterday\'s outdoor lunch period. A staff member is asking for a volunteer to help tidy things up.',
    cooperative: false,
  },
  {
    emoji: '🐾',
    title: 'Lost Campus Cat',
    description: 'The school\'s unofficial mascot, a tabby cat named Biscuit, has wandered off again. Can someone track him down before roll call?',
    cooperative: false,
  },
  {
    emoji: '🎒',
    title: 'Lost and Found Delivery',
    description: 'A pile of unclaimed items from the lost and found needs to be sorted and delivered to the right classrooms. A quick but important task!',
    cooperative: false,
  },
  {
    emoji: '🌱',
    title: 'Greenhouse Watering',
    description: 'The biology teacher forgot to water the greenhouse plants before heading to a staff meeting. The seedlings won\'t last long without help.',
    cooperative: false,
  },
  {
    emoji: '🖨️',
    title: 'Printer Jam Emergency',
    description: 'The main office printer is jammed right before a big exam handout. The secretary is panicking — someone tech-savvy is needed ASAP.',
    cooperative: false,
  },
  {
    emoji: '🍱',
    title: 'Cafeteria Delivery Mix-Up',
    description: 'A lunch order for the faculty lounge was sent to the wrong building. Someone needs to run it over before the food gets cold.',
    cooperative: false,
  },
  {
    emoji: '📋',
    title: 'Attendance Sheet Runner',
    description: 'The front office needs attendance sheets collected from three different classrooms before the end of first period. Time is ticking!',
    cooperative: false,
  },
  {
    emoji: '🔦',
    title: 'Flickering Hallway Light',
    description: 'A hallway light has been flickering all morning and it\'s distracting students. Maintenance needs someone to hold the ladder while they fix it.',
    cooperative: false,
  },
  {
    emoji: '🎨',
    title: 'Art Room Setup',
    description: 'The art teacher needs canvases and supply trays set up before the next class arrives. A helpful student could make a real difference.',
    cooperative: false,
  },
  {
    emoji: '📦',
    title: 'Supply Room Inventory',
    description: 'The supply closet is a disaster zone. A staff member needs a student to help count and organize the remaining stock before the week ends.',
    cooperative: false,
  },
  {
    emoji: '🏃',
    title: 'Urgent Message Relay',
    description: 'The intercom is down and a time-sensitive message needs to reach the gym coach immediately. Someone needs to sprint across campus.',
    cooperative: false,
  },
  {
    emoji: '🪴',
    title: 'Lobby Plant Rescue',
    description: 'The large decorative plant in the main lobby has tipped over and soil is everywhere. A student is needed to help clean it up before visitors arrive.',
    cooperative: false,
  },
  {
    emoji: '🎤',
    title: 'Mic Stand Setup',
    description: 'The auditorium needs microphone stands arranged for an afternoon assembly. The AV club is short-handed and needs one more volunteer.',
    cooperative: false,
  },
  {
    emoji: '🧪',
    title: 'Lab Equipment Return',
    description: 'A cart of chemistry lab equipment needs to be carefully wheeled back to the storage room after class. Steady hands required!',
    cooperative: false,
  },
  {
    emoji: '📰',
    title: 'Newsletter Distribution',
    description: 'The school newsletter just came off the printer and needs to be placed in every homeroom mailbox before the morning announcements.',
    cooperative: false,
  },
  {
    emoji: '🚪',
    title: 'Stuck Locker Door',
    description: 'A first-year student\'s locker is completely jammed and they\'re going to be late to class. Someone with a bit of strength could save the day.',
    cooperative: false,
  },
  {
    emoji: '🧊',
    title: 'Ice Pack Run',
    description: 'A student twisted their ankle during gym and the nurse\'s office is out of ice packs. Someone needs to grab ice from the cafeteria kitchen quickly.',
    cooperative: false,
  },
  {
    emoji: '📷',
    title: 'Yearbook Photo Assist',
    description: 'The yearbook photographer needs someone to hold a reflector panel for outdoor club photos. It\'s a small job but makes a big difference.',
    cooperative: false,
  },
  {
    emoji: '🎭',
    title: 'Drama Club Prop Mover',
    description: 'The drama club needs heavy stage props moved from the storage room to the auditorium stage before rehearsal. One strong volunteer needed.',
    cooperative: false,
  },
  {
    emoji: '🌦️',
    title: 'Weather Equipment Check',
    description: 'The school\'s rooftop weather station needs its sensors wiped down after last night\'s rain. The science teacher needs a careful volunteer.',
    cooperative: false,
  },
  {
    emoji: '🐟',
    title: 'Fish Tank Maintenance',
    description: 'The biology classroom\'s fish tank filter has stopped working. A student is needed to help the teacher swap it out before the fish suffer.',
    cooperative: false,
  },
  {
    emoji: '🏆',
    title: 'Trophy Case Dusting',
    description: 'The main hallway trophy case is looking dusty ahead of an open house event. The principal is asking for a volunteer to polish it up.',
    cooperative: false,
  },
  {
    emoji: '🎵',
    title: 'Music Room Chair Setup',
    description: 'The music room needs chairs arranged in a semicircle for the afternoon band practice. The teacher\'s back is acting up and needs assistance.',
    cooperative: false,
  },
  {
    emoji: '🔑',
    title: 'Key Return Errand',
    description: 'A set of classroom keys was left in the wrong office. Someone needs to retrieve them and return them to the right teacher before next period.',
    cooperative: false,
  },
  {
    emoji: '🧺',
    title: 'Laundry Room Assist',
    description: 'The PE department\'s towel laundry is done but no one is free to fold and sort it. A helpful student could knock this out in no time.',
    cooperative: false,
  },
  {
    emoji: '🖼️',
    title: 'Hallway Art Rehang',
    description: 'Several student art pieces fell off the hallway display wall overnight. The art teacher needs help re-hanging them before the school day begins.',
    cooperative: false,
  },
  {
    emoji: '🛒',
    title: 'Supply Store Run',
    description: 'The school store is running low on pencils and notebooks. A student is needed to carry a restock box from the main storage room.',
    cooperative: false,
  },
  {
    emoji: '🧯',
    title: 'Fire Drill Cone Placement',
    description: 'Safety cones need to be placed along the evacuation route before the scheduled fire drill. The safety officer needs a quick volunteer.',
    cooperative: false,
  },
  {
    emoji: '📡',
    title: 'Wi-Fi Router Reboot',
    description: 'The library\'s Wi-Fi router needs a manual reboot and the IT staff are tied up. A student who can follow simple instructions is needed.',
    cooperative: false,
  },
  {
    emoji: '🌸',
    title: 'Flower Arrangement Delivery',
    description: 'A bouquet meant for the front office reception desk was left in the parking lot. Someone needs to bring it inside before it wilts.',
    cooperative: false,
  },
  {
    emoji: '🎯',
    title: 'Target Range Cleanup',
    description: 'The training range has scattered target sheets and spent markers everywhere after morning practice. A volunteer is needed to tidy it up.',
    cooperative: false,
  },
  {
    emoji: '🧲',
    title: 'Science Fair Setup',
    description: 'Display boards and project tables need to be arranged in the gymnasium for tomorrow\'s science fair. One extra set of hands is all it takes.',
    cooperative: false,
  },
  {
    emoji: '🚿',
    title: 'Locker Room Towel Restock',
    description: 'The locker room towel dispensers are empty after a busy morning. A student is needed to grab fresh towels from the supply closet.',
    cooperative: false,
  },
  {
    emoji: '📬',
    title: 'Faculty Mail Sort',
    description: 'A large batch of mail arrived for the faculty and the office assistant is overwhelmed. A student volunteer can help sort it into the right boxes.',
    cooperative: false,
  },
  {
    emoji: '🎪',
    title: 'Event Banner Hanging',
    description: 'A banner for the upcoming school festival needs to be hung in the main hallway. The custodian needs someone to hold the other end.',
    cooperative: false,
  },
  {
    emoji: '🧸',
    title: 'Comfort Corner Setup',
    description: 'The counselor\'s office is setting up a new comfort corner with pillows and stuffed animals. A student is needed to help arrange everything.',
    cooperative: false,
  },
  {
    emoji: '🔧',
    title: 'Desk Wobble Fix',
    description: 'Several classroom desks have loose legs and are wobbling dangerously. Maintenance needs a student helper to hold desks steady while they tighten bolts.',
    cooperative: false,
  },
  {
    emoji: '🌡️',
    title: 'Thermostat Check',
    description: 'Multiple classrooms are reporting temperature issues. A student is needed to walk the building and note which rooms feel too hot or too cold.',
    cooperative: false,
  },
  {
    emoji: '🎲',
    title: 'Game Room Inventory',
    description: 'The student lounge game room needs its board games and pieces inventoried after a busy weekend. A detail-oriented volunteer is needed.',
    cooperative: false,
  },
  {
    emoji: '🏋️',
    title: 'Weight Room Equipment Reset',
    description: 'The weight room equipment was left out of place after an early morning session. The PE teacher needs a student to help reset everything.',
    cooperative: false,
  },
  {
    emoji: '🌿',
    title: 'Courtyard Leaf Sweep',
    description: 'Autumn leaves have piled up in the courtyard seating area. A student with a broom and ten minutes could make the space usable again.',
    cooperative: false,
  },
  {
    emoji: '📖',
    title: 'Library Book Reshelving',
    description: 'A cart of returned books is sitting in the library waiting to be reshelved. The librarian is swamped and would love a volunteer.',
    cooperative: false,
  },
  {
    emoji: '🎁',
    title: 'Birthday Decoration Setup',
    description: 'It\'s a staff member\'s birthday and the student council wants to decorate their classroom door as a surprise. One helper is needed to hang streamers.',
    cooperative: false,
  },
  {
    emoji: '🚦',
    title: 'Crosswalk Monitor',
    description: 'The usual crosswalk monitor called in sick. A responsible student is needed to help guide younger students safely across the street during dismissal.',
    cooperative: false,
  },
  {
    emoji: '🧴',
    title: 'Hand Sanitizer Restock',
    description: 'The hand sanitizer dispensers throughout the building are running low. A student is needed to refill them from the supply in the nurse\'s office.',
    cooperative: false,
  },
  {
    emoji: '🖥️',
    title: 'Computer Lab Shutdown',
    description: 'The computer lab was left on overnight and needs to be properly shut down before the first class arrives. A quick but important task.',
    cooperative: false,
  },
  {
    emoji: '🎓',
    title: 'Graduation Rehearsal Assist',
    description: 'The senior class is rehearsing graduation and needs a student to hand out programs and direct people to their seats in the auditorium.',
    cooperative: false,
  },
  {
    emoji: '🌊',
    title: 'Pool Equipment Check',
    description: 'The swim team\'s lane ropes need to be untangled and properly stored after practice. The coach needs one careful volunteer.',
    cooperative: false,
  },
  {
    emoji: '🗑️',
    title: 'Recycling Bin Roundup',
    description: 'The recycling bins throughout the school need to be emptied and brought to the loading dock before the pickup truck arrives.',
    cooperative: false,
  },
  {
    emoji: '🔔',
    title: 'Bell Schedule Posting',
    description: 'Updated bell schedule flyers need to be posted on every floor\'s bulletin board. A student with tape and a stack of papers can handle this.',
    cooperative: false,
  },
];

// ─── Cooperative Events (2–5 participants) ────────────────────────────────────
const COOPERATIVE_EVENTS = [
  {
    emoji: '🚨',
    title: 'Faculty Rescue Simulation',
    description: 'An entire rescue scenario is about to begin, but the instructors need several volunteers to play hero students for the exercise. This is a team effort!',
    participantsNeeded: null, // assigned randomly 2–5
    cooperative: true,
  },
  {
    emoji: '🏗️',
    title: 'Obstacle Course Assembly',
    description: 'The training department is setting up a new obstacle course on the back field and needs a crew of students to carry and position the heavy equipment.',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🎪',
    title: 'School Festival Booth Build',
    description: 'The upcoming school festival needs several booths constructed in the gymnasium. The student council is calling for a volunteer build crew right now.',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🌪️',
    title: 'Storm Damage Cleanup',
    description: 'Last night\'s storm knocked over several trees and scattered debris across the athletic field. A team of students is needed to clear the area before practice.',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🎬',
    title: 'Documentary Film Crew',
    description: 'The media class is filming a short documentary about campus life and needs a group of students to act as background extras and scene helpers.',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🏕️',
    title: 'Camping Trip Gear Load',
    description: 'The outdoor education class is heading out tomorrow and all the camping gear needs to be loaded onto the transport van. Many hands make light work!',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🎭',
    title: 'Play Rehearsal Stand-Ins',
    description: 'Several drama club members are absent and the director desperately needs stand-ins for today\'s full run-through. A group of willing volunteers is needed.',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🧱',
    title: 'Community Garden Build',
    description: 'The school\'s new community garden is being built today and the horticulture teacher needs a team to help lay down the raised bed frames and fill them with soil.',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🚌',
    title: 'Field Trip Chaperone Assist',
    description: 'A field trip is departing soon and the teacher needs a group of responsible older students to help supervise and keep the younger kids organized.',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🏆',
    title: 'Trophy Room Renovation',
    description: 'The trophy room is getting a full makeover and needs a team to carefully move display cases, clean shelves, and reorganize decades of awards.',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🎆',
    title: 'Pep Rally Setup Crew',
    description: 'The big pep rally is in two hours and the gymnasium still needs bleachers unfolded, banners hung, and the sound system tested. All hands on deck!',
    participantsNeeded: null,
    cooperative: true,
  },
  {
    emoji: '🌍',
    title: 'Cultural Fair Booth Setup',
    description: 'The annual cultural fair opens this afternoon and several booths still need tables, tablecloths, and display materials arranged. A team is needed now.',
    participantsNeeded: null,
    cooperative: true,
  },
];

module.exports = { EVENTS, COOPERATIVE_EVENTS };
